from fpdf import FPDF
class PDF(FPDF):
    def doc_title(self, label):
        self.set_font('helvetica', 'B', size=16)
        self.cell(0, 10, label, 0, 1, 'L')
        self.ln()
    def doc_text(self, text):
        self.set_font('helvetica', '', size=12)
        self.multi_cell(0, 7, text)
        self.ln()
    def doc_img(self, img, x, y, w, h):
        self.image(img, x, y, w, h)
pdf = PDF()
pdf.add_page()
pdf.doc_title("Vagas por categoria administrativa em São Paulo")
pdf.doc_text("O acesso à educação superior é um componente crucial para o desenvolvimento social e econômico de um país. No Brasil, as instituições de ensino superior estão divididas em diferentes categorias, incluindo faculdades privadas com fins lucrativos, privadas sem fins lucrativos e instituições públicas estaduais, federais e municipais. Este relatório tem como objetivo fornecer uma visão geral da distribuição de vagas nessas categorias.")
pdf.doc_img("vagas_por_cat.png", 50, 70, 100, 80)
pdf.ln(75)
pdf.doc_text("1. Faculdades Privadas com Fins Lucrativos. As instituições de ensino superior privadas com fins lucrativos desempenham um papel significativo na oferta de cursos e vagas no Brasil. Essas instituições muitas vezes buscam o lucro e, como resultado, podem adotar diferentes estratégias em relação aos valores das mensalidades e programas oferecidos.")
pdf.doc_text("2. Faculdades Privadas sem Fins Lucrativos. Outro subsetor importante é representado por instituições privadas sem fins lucrativos. Essas instituições têm uma abordagem mais voltada para o benefício social, embora ainda atuem como organizações privadas. Elas podem receber apoio financeiro de entidades filantrópicas ou religiosas.")
pdf.doc_text("3. Instituições Públicas Estaduais. As universidades e faculdades estaduais são mantidas pelos governos dos estados brasileiros. Elas desempenham um papel crucial na democratização do acesso ao ensino superior, oferecendo cursos em uma variedade de disciplinas.")
pdf.doc_text("4. Instituições Públicas Federais. As instituições federais, sob a jurisdição do governo federal, são reconhecidas por sua excelência acadêmica. Elas geralmente recebem um alto investimento público e oferecem uma ampla gama de cursos, contribuindo significativamente para a pesquisa e o desenvolvimento científico.")
pdf.doc_text("5. Instituições Públicas Municipais. Em alguns casos, municípios brasileiros mantêm suas próprias instituições de ensino superior. Embora o número de vagas nessas instituições possa ser menor em comparação com as estaduais e federais, elas desempenham um papel importante na oferta de oportunidades educacionais locais.")
pdf.doc_text("Conclusão. A diversidade de instituições de ensino superior no Brasil reflete a complexidade do sistema educacional do país. Cada categoria tem seu papel único na promoção do acesso à educação superior. Para obter informações mais precisas e recentes sobre a quantidade de vagas em cada categoria, recomenda-se consultar fontes oficiais, como os órgãos reguladores da educação no Brasil e as próprias instituições de ensino.")
pdf.ln(70)
pdf.doc_img("vagas.png", 50, 100, 100, 80)
pdf.ln(30)
pdf.doc_text("A disparidade no acesso à educação superior entre ricos e pobres é uma realidade que merece atenção crítica. A observação de que alguns indivíduos financeiramente privilegiados frequentam instituições públicas enquanto outros menos abastados recorrem a instituições privadas revela uma inversão preocupante das expectativas sociais.")
pdf.doc_text("Aspectos Positivos. É inegável que as instituições públicas de ensino superior muitas vezes oferecem um padrão de qualidade educacional excepcional. A presença de estudantes mais afluentes nesses ambientes pode contribuir para uma diversidade de perspectivas, enriquecendo o ambiente acadêmico e estimulando o intercâmbio de ideias.")
pdf.doc_text("Desigualdades Financeiras. Contudo, a tendência de alguns estudantes ricos optarem por instituições públicas enquanto outros, de recursos mais limitados, buscam opções privadas destaca as profundas desigualdades financeiras que permeiam o acesso à educação no Brasil. A educação, que deveria servir como um equalizador social, muitas vezes reproduz e perpetua as divisões econômicas existentes.")
pdf.doc_text("Reflexo das Políticas Educacionais. Essa realidade reflete, em parte, as deficiências nas políticas educacionais. A falta de investimentos adequados nas instituições públicas pode criar um ambiente em que apenas os mais afortunados podem aproveitar plenamente os benefícios de uma educação superior de qualidade, enquanto outros se veem forçados a buscar alternativas onerosas.")
pdf.doc_text("A Importância da Mudança. Uma sociedade justa deve buscar corrigir essas discrepâncias. Investimentos substanciais em instituições públicas, programas de bolsas de estudo e políticas que promovam a equidade no acesso à educação superior são cruciais. A educação deve ser vista como um direito fundamental, não um privilégio reservado apenas àqueles que podem arcar com as despesas.")
pdf.doc_text("Conclusão. O fenômeno de ricos frequentando instituições públicas e pobres recorrendo a faculdades privadas destaca a necessidade urgente de repensar e reformar o sistema educacional brasileiro. A verdadeira igualdade de oportunidades só será alcançada quando o acesso à educação superior não estiver mais atrelado ao poder aquisitivo, mas sim à meritocracia e ao compromisso social com a construção de uma sociedade mais justa e inclusiva.")
pdf.output("educa.pdf")